// Code generated by Fern. DO NOT EDIT.

package jsklanEmpty

import (
	core "github.com/jsklan/test-fern-app-perms/core"
	internal "github.com/jsklan/test-fern-app-perms/internal"
)

var ErrorCodes internal.ErrorCodes = internal.ErrorCodes{
	404: func(apiError *core.APIError) error {
		return &MovieDoesNotExistError{
			APIError: apiError,
		}
	},
}
