// Code generated by Fern. DO NOT EDIT.

package imdb

import (
	context "context"
	testfernappperms "github.com/jsklan/test-fern-app-perms"
	core "github.com/jsklan/test-fern-app-perms/core"
	internal "github.com/jsklan/test-fern-app-perms/internal"
	option "github.com/jsklan/test-fern-app-perms/option"
)

type Client struct {
	WithRawResponse *RawClient

	options *core.RequestOptions
	baseURL string
	caller  *internal.Caller
}

func NewClient(options *core.RequestOptions) *Client {
	return &Client{
		WithRawResponse: NewRawClient(options),
		options:         options,
		baseURL:         options.BaseURL,
		caller: internal.NewCaller(
			&internal.CallerParams{
				Client:      options.HTTPClient,
				MaxAttempts: options.MaxAttempts,
			},
		),
	}
}

// Add a movie to the database
func (c *Client) CreateMovie(
	ctx context.Context,
	request *testfernappperms.CreateMovieRequest,
	opts ...option.RequestOption,
) (testfernappperms.MovieID, error) {
	response, err := c.WithRawResponse.CreateMovie(
		ctx,
		request,
		opts...,
	)
	if err != nil {
		return "", err
	}
	return response.Body, nil
}

// Retrieve a movie from the database based on the ID
func (c *Client) GetMovie(
	ctx context.Context,
	id testfernappperms.MovieID,
	opts ...option.RequestOption,
) (*testfernappperms.Movie, error) {
	response, err := c.WithRawResponse.GetMovie(
		ctx,
		id,
		opts...,
	)
	if err != nil {
		return nil, err
	}
	return response.Body, nil
}
